### ISSUE TITLE
请问你是如何确定NearbyEquipment之后跟的地址的？我用洗衣页面显示的机器地址查询，查询出来的列表是空的.

### ISSUE THREAD

**Issue by wang-jt** [bestsvip/see-xiyiji#1]
如题

**Comment by bestsvip** [comment]
我只是想看我们学校的洗衣机状态，但是它要先登录然后才能看，我就做了个网页简化我查看洗衣机状态的步骤，其他学校的洗衣机可能用不了
________________________________
发件人: Jayten (Juntao) Wang ***@***.***>
发送时间: 2024年9月1日 14:22
收件人: bestsvip/see-xiyiji ***@***.***>
抄送: Subscribed ***@***.***>
主题: [bestsvip/see-xiyiji] 请问你是如何确定NearbyEquipment之后跟的地址的？我用洗衣页面显示的机器地址查询，查询出来的列表是空的. (Issue #1)


如题

―

**Comment by bestsvip** [comment]
我只是想看我们学校的洗衣机状态，但是它要先登录然后才能看，我就做了个网页简化我查看洗衣机状态的步骤，其他学校的洗衣机可能用不了
